### ISSUE TITLE
emcee_fit function needs to be cleaned up

### ISSUE THREAD

**Issue by barkls** [phys201/multstars#10]
The function `emcee_fit` closely follows code from a section notebook. This isn't a problem by itself, but the code hasn't been sufficiently modified to fit into your package. For example, it's highly unlikely you will want to use a Metropolis Hastings sampler for this project so you should remove that. Similarly, the number of steps (100) probably isn't enough to be thoroughly burned-in so you should check that as well.

**Comment by jgillis16** [comment]
we're switching over to pymc3 (following vinny's suggestion)

**Comment by barkls** [comment]
Even though you have switched to pymc3, you have some similar problems. For example, there's still an option for Metropolis sampling in your code and there are warnings about only sampling from a single chain. In general, it's fine to use code from outside sources (such as class resources) for the project but you need to make sure to adapt it to your particular needs and not just use it as-is.
