### ISSUE TITLE
Assessing inference results

### ISSUE THREAD

**Issue by gloriaha** [phys201/multstars#23]
I'm not sure if you know the true parameters for this dataset, but it would be nice to be able to compare your results to some orthogonal metric.  Even just plotting the pymc3 MAP fit on the data histogram and comparing it to your previous guesses would be a nice way to visualize the inference results.  

Also, not sure if the current quantile display is the best way to report the upper and lower quantiles -- unclear what the + 10 - 9 means, maybe there's a better way to display?

**Comment by cmlamman** [comment]
no longer using quantiles in tutorial.

Other suggestion still stands and is part of issue 27 now
