### ISSUE TITLE
synthetic data doesn't match generative model

### ISSUE THREAD

**Issue by barkls** [phys201/multstars#34]
The steps to create the synthetic data don't match the generative model used in inference calculations.  These two processes should correspond as closely as possible, ideally by using the generative model to create the synthetic data. Otherwise it's hard to figure out whether any discrepancies between true and inferred values are due to problems with the inference routine or differences between the models.

**Comment by vditomasso** [comment]
Edited the creation of the synthetic data (up until the data truncation) to match the generative model. We're going to work on getting the truncation part of the generative model to be more like the creation of the synthetic data

commit 79ac828a3346438ee087a596c87bd10186d1b243 and commit 8bdb00021a54d618e61deb00d1653ce4a548cf9b
