### ISSUE TITLE
model is complicated

### ISSUE THREAD

**Issue by barkls** [phys201/multstars#35]
This isn't necessarily a problem in and of itself, but it's hard to interpret, as well as diagnose and test. It would be nice to see the model broken up into a series of steps of increasing complexity so that a simpler inference problem could be evaluated first.

**Comment by cmlamman** [comment]
Is the current, much more organized and well-commented, version sufficient? I think it would be difficult to break this into any simpler (meaningful) inference problems since each part is reliant on the others. Although perhaps I just don't understand what you're suggesting.

**Comment by barkls** [comment]
My point was that the complexity of the model makes it difficult to understand exactly what's going on behind the scenes, which in turn makes it difficult to test and troubleshoot. It would have been nice to see a few levels of model (e.g an intermediate step where no observations are cut - make sure the model/inference works in a an imaginary situation where you *could* collect all data), but I realize pymc3 doesn't make this straightforward. Your current model works and is well-documented, so I'm closing the issue.
